// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBABPNOt_GEoOlu2VYdbJ2BQ6s3-bCSphE',
    appId: '1:351577808102:web:0f3c5185888a89913eef27',
    messagingSenderId: '351577808102',
    projectId: 'flutterlogin-f9639',
    authDomain: 'flutterlogin-f9639.firebaseapp.com',
    storageBucket: 'flutterlogin-f9639.appspot.com',
    measurementId: 'G-SKCR6F4687',
    databaseURL: 'https://flutterlogin-f9639-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsBO2dJ1P7KfktLUoUpyVoAFLJ27ulVes',
    appId: '1:351577808102:android:0c22cf332f172f2c3eef27',
    messagingSenderId: '351577808102',
    projectId: 'flutterlogin-f9639',
    storageBucket: 'flutterlogin-f9639.appspot.com',
    databaseURL: 'https://flutterlogin-f9639-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjaLMzQEboEIfImjXU22Bhs1JLLk_sjk',
    appId: '1:351577808102:ios:e26bee3f5e75287c3eef27',
    messagingSenderId: '351577808102',
    projectId: 'flutterlogin-f9639',
    storageBucket: 'flutterlogin-f9639.appspot.com',
    iosClientId: '351577808102-no3fi4vhnvgshe35cg8q9j9hejs66utl.apps.googleusercontent.com',
    iosBundleId: 'com.firzen.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzjaLMzQEboEIfImjXU22Bhs1JLLk_sjk',
    appId: '1:351577808102:ios:e26bee3f5e75287c3eef27',
    messagingSenderId: '351577808102',
    projectId: 'flutterlogin-f9639',
    storageBucket: 'flutterlogin-f9639.appspot.com',
    iosClientId: '351577808102-no3fi4vhnvgshe35cg8q9j9hejs66utl.apps.googleusercontent.com',
    iosBundleId: 'com.firzen.flutterLogin',
  );
}
